server:
  port: 8888
db:
  username: sa
  pwd: 123

#docker run --name mysql -p 3307:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.7
spring:
  jpa:
    show-sql: false
    hibernate:
      dll-auto: create
  datasource:
    url: jdbc:mysql://localhost:3307/demo?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
